//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sach_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class NhaXuatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXuatBan()
        {
            this.Saches = new HashSet<Sach>();
        }

        [DisplayName("Mã NXB")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        public string MaNXB { get; set; }

        [DisplayName("Tên Nhà Xuất Bản")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        public string TenNXB { get; set; }

        [DisplayName("Địa Chỉ")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        public string DiaChi { get; set; }

        [DisplayName("Điện Thoại")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\d+$", ErrorMessage = "{0} chỉ được chứa các chữ số.")]
        public string DienThoai { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        [EmailAddress(ErrorMessage = "Định dạng {0} không hợp lệ.")]
        public string Email { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
