//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sach_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Sach
    {
        [DisplayName("Mã Sách")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        public string MaSach { get; set; }

        [DisplayName("Tên Sách")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        public string TenSach { get; set; }

        [DisplayName("Tác Giả")]
        [Required(ErrorMessage = "Vui lòng chọn {0}.")]
        public string MaTG { get; set; }

        [DisplayName("Thể Loại")]
        [Required(ErrorMessage = "Vui lòng chọn {0}.")]
        public string MaTL { get; set; }

        [DisplayName("Nhà Xuất Bản")]
        [Required(ErrorMessage = "Vui lòng chọn {0}.")]
        public string MaNXB { get; set; }

        [DisplayName("Năm Xuất Bản")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        [Range(1900, 2100, ErrorMessage = "{0} phải từ năm {1} đến {2}.")]
        public Nullable<int> NamXuatBan { get; set; }

        [DisplayName("Giá Bìa")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        [Range(0, double.MaxValue, ErrorMessage = "{0} phải lớn hơn hoặc bằng 0.")]
        [DataType(DataType.Currency)]
        public Nullable<decimal> GiaBia { get; set; }

        [DisplayName("Số Lượng Tồn")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        [Range(0, int.MaxValue, ErrorMessage = "{0} không được âm.")]
        public Nullable<int> SoLuongTon { get; set; }

        public virtual NhaXuatBan NhaXuatBan { get; set; }
        public virtual TacGia TacGia { get; set; }
        public virtual TheLoai TheLoai { get; set; }
    }
}
