//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_Sach_Nhom.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TheLoai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TheLoai()
        {
            this.Saches = new HashSet<Sach>();
        }

        [DisplayName("Mã Thể Loại")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        public string MaTL { get; set; }

        [DisplayName("Tên Thể Loại")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        public string TenTL { get; set; }

        [DisplayName("Mô Tả")]
        [Required(ErrorMessage = "{0} không được để trống.")]
        [DataType(DataType.MultilineText)] 
        public string MoTa { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sach> Saches { get; set; }
    }
}
